language: r
warnings_are_errors: true

env:
  matrix:
   - NOT_CRAN="true"
   - NOT_CRAN="false"

r_build_args:
   - --no-manual --no-build-vignettes

r_check_args:
   - --no-manual --no-build-vignettes --as-cran

r_github_packages:
   - jimhester/covr
   - jimhester/lintr

after_success:
  - Rscript -e 'library(covr);coveralls()'
