# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

env:
   global:
     - WARNINGS_ARE_ERRORS=1
     - R_BUILD_ARGS="--no-manual --no-build-vignettes"
     - R_CHECK_ARGS="--no-manual --no-build-vignettes --as-cran"
     - BOOTSTRAP_LATEX=""
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package igraph/rigraph@d121eb948404766ece8583cadf6708c0ccc748ee
  - ./travis-tool.sh github_package jimhester/covr@4cae287abde5e2cf0c3c73aedeaec4d902dfd3ed
  - ./travis-tool.sh github_package jimhester/lintr@21607f469c2ce4f999d04a836f9348038a7282e2
  - ./travis-tool.sh github_package hadley/devtools@52bc15bb7eb87105bbf799d7f784054921146c02
  - ./travis-tool.sh github_package hadley/testthat@c67018fa4970ee3390ea2056efe56726626b07e3

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
