# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
# https://github.com/craigcitro/r-travis/wiki

language: c

env:
   global:
     - WARNINGS_ARE_ERRORS=1
     - R_BUILD_ARGS="--no-manual"
     - R_CHECK_ARGS="--no-manual --as-cran"
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package jimhester/covr
  - ./travis-tool.sh github_package jimhester/lintr

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'library(covr);coveralls()'
  - Rscript -e 'lintr::lint_package(linters=c(assignment_linter, single_quotes_linter, absolute_paths_linter, no_tab_linter, commas_linter, spaces_left_parentheses_linter, spaces_inside_linter, open_curly_linter, closed_curly_linter, snake_case_linter, multiple_dots_linter, object_length_linter, object_usage_linter, trailing_whitespace_linter, trailing_blank_lines_linter))'

#Linters to add:   line_length_linter (181), infix_spaces_linter (73)
